import React, { Component } from "react";
import ReactDOM from "react-dom";
//import "./TableStyle.css";
import "./style.css";
//import "https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css";

class Table extends Component {
    constructor() {
        super();
    }

    render() {
        return (
            <div>
                <section>
                    <h1>Tecnologias para la Web</h1>
                    <div class="tbl-header">
                        <table cellpadding="0" cellspacing="0" border="0">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>NOMBRE</th>
                                    <th>FECHA</th>
                                    <th>MODIFICAR</th>
                                    <th>ELIMINAR</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="tbl-content">
                        <table cellpadding="0" cellspacing="0" border="0">
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>GRAFICA_1</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>GRAFICA_2</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>GRAFICA_3</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>GRAFICA_4</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>GRAFICA_5</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>6</td>
                                    <td>GRAFICA_6</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>7</td>
                                    <td>GRAFICA_7</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>8</td>
                                    <td>GRAFICA_8</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>9</td>
                                    <td>GRAFICA_9</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>10</td>
                                    <td>GRAFICA_10</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>11</td>
                                    <td>GRAFICA_11</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>12</td>
                                    <td>GRAFICA_12</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>13</td>
                                    <td>GRAFICA_13</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>14</td>
                                    <td>GRAFICA_14</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>15</td>
                                    <td>GRAFICA_15</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>16</td>
                                    <td>GRAFICA_16</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>17</td>
                                    <td>GRAFICA_17</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>18</td>
                                    <td>GRAFICA_18</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>19</td>
                                    <td>GRAFICA_19</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>20</td>
                                    <td>GRAFICA_20</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>21</td>
                                    <td>GRAFICA_21</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>22</td>
                                    <td>GRAFICA_22</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>23</td>
                                    <td>GRAFICA_23</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>24</td>
                                    <td>GRAFICA_24</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>25</td>
                                    <td>GRAFICA_25</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>26</td>
                                    <td>GRAFICA_26</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>27</td>
                                    <td>GRAFICA_27</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>28</td>
                                    <td>GRAFICA_28</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>29</td>
                                    <td>GRAFICA_29</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>30</td>
                                    <td>GRAFICA_30</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>31</td>
                                    <td>GRAFICA_31</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                                <tr>
                                    <td>32</td>
                                    <td>GRAFICA_32</td>
                                    <td>17/11/19</td>
                                    <td>MODIFICAR</td>
                                    <td>ELIMINAR</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </section>

                <div class="made-with-love">
                    Made with
              <i>♥</i> by Ramses, Scarlott y Paz
            </div>

                <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script><script src="./script.js"></script>
            </div>
        );
    }
}

export default Table;